name: Code quality

on:
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout repository
        uses: actions/checkout@v2 

      - name: Install dependencies
        run: yarn

      - name: Lint code
        run: yarn lint

      - name: Typecheck code
        run: yarn typecheck

      - name: Test code
        run: yarn test
